import { Modals } from "@/compoents/molecules";
import { RootFooter, RootMain, RootHeader } from "@/compoents/templates";
import { NextUIProvider } from "@nextui-org/system";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { ReactNode } from "react";

import { ApolloWrapper } from "@/lib/client";
import { cookiesKeys } from "@/utils/variables";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) {
  const cookieStore = cookies();
  const isCloseBanner =
    cookieStore.get(cookiesKeys.isCloseBanner)?.value === "true";
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <ApolloWrapper>
          <NextUIProvider className="w-full flex flex-col relative min-h-[100dvh]">
            <RootHeader isCloseBanner={isCloseBanner} />
            <RootMain>{children}</RootMain>
            <RootFooter />
            <Modals />
          </NextUIProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
