import { Main } from "@/compoents/atoms";
import { RootHeader, RootFooter } from "@/compoents/organisms";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body
        className={clsx(
          inter.className,
          "max-w-screen-xl w-full px-4 box-border"
        )}
      >
        <RootHeader />
        <Main>{children}</Main>
        <RootFooter />
      </body>
    </html>
  );
}
